title: "Christian Henning"
description: "Software & Data Engineering · AI · Analytics"
theme: jekyll-theme-minimal  # built-in GH Pages theme
url: "https://chhenning.github.io"

# Optional: social links to show in footer
github_username: chhenning
linkedin_username: chhenning